#!/bin/bash
cd Desktop/OS-project/
function update() {
  python login.py
}

function run() {
  python /home/kushal/Desktop/OS-project/pyfile.py
}

function display() {
  tablign data.csv
  echo -e "\n"
}

if [ "$1" == "-i" ]; then
  update
elif [ "$1" == "-r" ]; then
  run
elif [ "$1" == "-d" ]; then
  display
else
  echo "Usage: kletech [options]"
  echo "Options:"
  echo "  -i, --initialize: Initialize usn and dob"
  echo "  -r, --run: Fetch the attendence"
  echo "  -d, --display: display recent fetched data"
fi
