#!/bin/bash

function update() {
  echo "Updating software..."
  python login.py
}

function run() {
  python pyfile.py
}

function display() {
  tablign data.csv
}

if [ "$1" == "-i" ]; then
  update
elif [ "$1" == "-r" ]; then
  run
elif [ "$1" == "-d" ]; then
  display
else
  echo "Usage: kletech [options]"
  echo "Options:"
  echo "  -i, --initialize: Initialize usn and dob"
  echo "  -r, --run: Fetch the attendence"
  echo "  -d, --display: display recent fetched data"
fi
